### ISSUE TITLE
Rebrand to Qiskit Serverless

### ISSUE THREAD

**Issue by pandasa123** [Qiskit/qiskit-serverless#1307]
## Background

As Serverless is integrating into the Qiskit stack, we want to rebrand Quantum Serverless to match. This issue represents the early items for May 20th

### Development

- [x] Rename repo from `quantum-serverless` to `qiskit-serverless`
  - [x] #1308  
- [x] Move repo from `Qiskit-Extensions` to `Qiskit`
- [x] Update PyPi name from `quantum-serverless` to `qiskit-serverless`
  - [x] [Deploy Qiskit Serverless to PyPi](https://pypi.org/project/qiskit-serverless/)
  - [x] #1326 

### Content

- [x] [Update documentation](https://github.com/Qiskit/documentation/blob/main/docs/run/quantum-serverless.mdx)
  - [x] [PR for documentation content changes ](https://github.com/Qiskit/documentation/pull/1292)
  - [x] @Eric-Arellano for redirections for URL directions
- [x] [Update tutorials in IBM Quantum Learning](https://github.ibm.com/IBM-Q-Software/ibm-quantum-learning-enablement/pull/113)
- [x] [Update Qiskit Ecosystem](https://github.com/Qiskit/ecosystem/issues/717) (@frankharkins)
- [x] Update README

**Comment by psschwei** [comment]
Are we going to maintain backwards compatibility? In particular, wondering if older clients will still work after we make these changes, or will this require users to update to the latest (qiskit-serverless) version of the client?

**Comment by pandasa123** [comment]
@psschwei, given that this project is in alpha, we should make these changes without backwards compatibility considerations yet

@garrison, I think that's a great idea...and I'd imagine there's a bit of flexibility to get the rebrand completed first, and adjust pipelines after

**Comment by Tansito** [comment]
Following @garrison comment I added the PR to deprecate quantum-serverless

**Comment by pandasa123** [comment]
All the tasks are completed, will close this epic. 

Excellent work everyone
